### ISSUE TITLE
liscense file doesn't exist error

### ISSUE THREAD

**Issue by JasonStoltz** [ghaiklor/generator-es6-npm-module#41]
`.../.cache/yeoman/github/choosealicense.com/gh-pages/_licenses/unlicense.txt doesn't exist`

It looks like the files exist at that location, but they have a `.html` extension, not `.txt`

**Comment by ghaiklor** [comment]
@JasonStoltz which license you choose ?

**Comment by JasonStoltz** [comment]
"mit", "unliscense" ... any of them give me this error. Because it's looking for ".txt" files, and there are only ".html" files in that directory.

```
→ls
afl-3.0.html        bsd-2-clause.html   epl-1.0.html        isc.html        mit.html        ms-rl.html      wtfpl.html
agpl-3.0.html       bsd-3-clause-clear.html eupl-1.1.html       lgpl-2.1.html       mit.txt         ofl-1.1.html
apache-2.0.html     bsd-3-clause.html   gpl-2.0.html        lgpl-3.0.html       mpl-2.0.html        osl-3.0.html
artistic-2.0.html   cc0-1.0.html        gpl-3.0.html        lppl-1.3c.html      ms-pl.html      unlicense.html
```

I had to manually create a `mit.txt` file to get this generator to work.

**Comment by ghaiklor** [comment]
@JasonStoltz yep, they are change txt to html. Thanks for report. I'll update this soon.

**Comment by ghaiklor** [comment]
@JasonStoltz published under new version.
